### ISSUE TITLE
How to run SRVPro with docker?

### ISSUE THREAD

**Issue by Highwall2016** [mycard/srvpro#27]
Sorry, I am not sure whether I did something wrong?  It is not work that I followed the steps of Wiki.

`docker pull mycard/ygopro-server`
`mkdir expansions config`
`docker run -d -p 7911:7911 -p 7922:7922 -v $PWD/config:/ygopro-server/config -v $PWD/expansions:/ygopro-server/ygopro/expansions --name=ygopro-server --restart=always mycard/ygopro-server`

but i open the browser at port 7911, there is not things

**Comment by mercury233** [comment]
it isn't a http server, you should use ygopro to connect to the 7911 port

**Comment by Highwall2016** [comment]
> it isn't a http server, you should use ygopro to connect to the 7911 port

Thanks your so fast reply.
Does it mean to use this 
[](http://srvpro.ygo233.com/dashboard.html)
So, I can't use docker to play the ADS.

**Comment by mercury233** [comment]
I can't understand what you mean.

**Comment by Highwall2016** [comment]
> I can't understand what you mean.

Sorry, I think I misunderstood the srvpro.
If I want to play ygopro, I should install with .exe? not docker image.
but I am using ubuntu. Is any way could I do?

**Comment by mercury233** [comment]
Oh you mean you want to play the game, not host a server. In this situation you can try to build the mycard fork of ygopro https://github.com/mycard/ygopro
see .travis.yml for details

**Comment by Highwall2016** [comment]
> Oh you mean you want to play the game, not host a server. In this situation you can try to build the mycard fork of ygopro https://github.com/mycard/ygopro
> see .travis.yml for details

Really thank your help ~~
