### ISSUE TITLE
How do I make srvpro recognize my card scripts?

### ISSUE THREAD

**Issue by botist** [mycard/srvpro#32]
Tried placing them in `/ygopro-server/ygopro/expansions/` and `/ygopro-server/ygopro/script/`, no luck. Managed to get it to recognize the databases tho

**Comment by mercury233** [comment]
`ygopro/expansions/*.cdb`
`ygopro/expansions/script/*.lua`

**Comment by botist** [comment]
I tried placing them there too, at `ygopro-server\expansions\script` but nothing still

**Comment by botist** [comment]
The issue most likely was: the scripts weren't compatible with the server. Thanks @mercury233!
