### ISSUE TITLE
服务器能否读取expansions下的ypk文件？

### ISSUE THREAD

**Issue by pf666nb** [mycard/srvpro#69]
在部署自己的卡片脚本时，我按照expansions/*.cdb和script/*.lua来部署，客户端能够正常识别，当diy的卡多起来的时候，我注意到类似先行卡更新是直接打包成ypk文件然后放置在expansions文件下即可，我立刻尝试将diy的卡也打包成一样的结构放置到服务器的expansions下，但是疑惑的是客户端机显示主机无法识别卡片，请问是服务器不支持读取ypk文件，只能按照原始的方法读取吗？还是需要不同的方法才能正常的读取，我是使用docker镜像部署的，不知道是否与这个有关系，如果有其他的读取方法希望能够提供，谢谢

**Comment by mercury233** [comment]
编译服务端的ygopro时需要定义SERVER_ZIP_SUPPORT，因为需要irrlicht，所以默认是不带的

**Comment by pf666nb** [comment]
抱歉，我可能不是太听得懂，意思是docker镜像部署的ygopro不支持直接读取expansions下的ypk文件是吗？只能手动的部署

**Comment by mercury233** [comment]
改dockerfile应该也是可以实现的

**Comment by pf666nb** [comment]
请问是需要修改Dockerfile.lite文件吗？如果是的话，请问需要修改或者增加哪个参数？

**Comment by mercury233** [comment]
加参数还不够，需要再加上获取irrlicht的步骤，我没有测试过

**Comment by pf666nb** [comment]
好的，非常感谢您百忙之中抽空回答我的问题，剩下的我会自己去研究的
