### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by wolverine998** [mycard/srvpro#74]
Hello. Cannot connect to server, i'm using YgoPro2 1.034B version. Also changing the Language in config file has no effect.

What should i do, i don't understand chinese

**Comment by mercury233** [comment]
Sorry, I can't get what you had done and what do you want to do.

**Comment by wolverine998** [comment]
I managed to get it working. But i cannot set trap or spell cards, it doesnt allows me to. Maybe the client messages definitions are different than servers. Using YgoPro2 version 1.034B
