### ISSUE TITLE
官方更新的新卡（非 先行卡），本地服务怎么升级？

### ISSUE THREAD

**Issue by rRiInNgG** [mycard/srvpro#75]
官方更新的新卡（非 先行卡），本地服务怎么升级？只能通过SRVPro Dashboard更新吗？

**Comment by mercury233** [comment]
非docker的话用git pull之后再重新build

**Comment by rRiInNgG** [comment]
我用的就是docker部署的。

**Comment by rRiInNgG** [comment]
是不是重新用docker file生成新镜像就可以了？不考虑以往的对战信息保留的话。

**Comment by mercury233** [comment]
刚刚更新了 git-registry.mycard.moe/mycard/srvpro 上的 image ，pull之后应该可以用了

**Comment by rRiInNgG** [comment]
好的，我试试。谢谢。
